### ISSUE TITLE
Make addon filtering by name more forgiving

### ISSUE THREAD

**Issue by andyhot** [emberobserver/server#61]
It's already possible to request https://www.emberobserver.com/api/v2/addons?filter[name]=ember-inline-edit,ember-cli-sass and get details on those 2 (or more) addons.

If however one of the names is unknown to the server (perhaps a really new addon, or a misspelt one, i.e. https://www.emberobserver.com/api/v2/addons?filte[name]=ember-inline-edit,ember-cli-sasss), the response becomes a 404 (with a message of The record identified by ember-cli-sasss could not be found)

Is it possible to change this behavior and return data for the addons that match the request?

**Comment by kategengler** [comment]
Unfortunately, we're not prepared to support the API as public at this time. It can change at any time and I don't recommend relying on it. 

If you're looking to search addons as a user, I recommend using the site or making use of the opensearch capability http://g.recordit.co/KOeMOW6LgN.gif

**Comment by andyhot** [comment]
ok, thx for the heads up
