### ISSUE TITLE
Add Skylight Instrumentation

### ISSUE THREAD

**Issue by vaidehijoshi** [emberobserver/server#63]
Hi there! 👋 

I work at Skylight, a smart profiler for Rails apps. I was wondering if you'd be interested in a free Skylight account to help make it easy for you and your contributors to pinpoint performance issues in Rails applications. My coworker @chancancode mentioned that you'd be a great candidate for a free account! 😄

We work on a lot of open source projects ourselves, and in our experience it can be pretty hard to get contributors to work on application performance issues. Few contributors consider working on performance problems, and the ones that might be interested may not even know where to start. By making performance information more accessible, we hope to inspire potential contributors to tackle slow parts of your app, and have a good way to see if their contributions helped.

For reference, [this](https://oss.skylight.io/app/applications/g0gJSNnzYAws/) is the Skylight dashboard we set up for [The Odin Project](https://www.theodinproject.com/). It should give you a pretty good idea of how Skylight works.

Integrating Skylight to a Rails application is very easy. All you have to do is add the gem to your Gemfile and set an environment variable with your authentication token. (I am also happy to send a pull request, too!).

If you’re interested in setting this up or if you have any questions, you can reach us here or at support@skylight.io. You can also sign up for a free Skylight account on our Open Source [landing page](https://www.oss.skylight.io), which is where we feature some of our favorite open source apps. We'd love to feature you on there, too! We hope you’ll join us in helping to make performance an accessible way to contribute to an open source project :)

**Comment by kategengler** [comment]
Hi @vaidehijoshi! I'd love to have Skylight for EmberObserver. I once had it set up but found out quickly that we had many more requests per month than I ever imagined 😂 

Do you prefer I sign up on the landing page?

**Comment by vaidehijoshi** [comment]
@kategengler YAY! I'm so glad you're interested :) And yes, if you sign up via the landing page, your request will go into our internal ticketing system which will help us keep track of your account. The next step in our [open source setup guide](https://www.skylight.io/support/skylight-for-open-source#setup) is to create an account and manually add your app. I'll switch on open source mode once you've created your app :)

**Comment by kategengler** [comment]
Great -- I saw your email and will continue with that as soon as I can. Unfortunately I am having a very busy week, but the latest I'll get to it is next week!

**Comment by vaidehijoshi** [comment]
Hi Katie! 👋 Just following up on this; let me know if you need my help or if you have any questions :)

**Comment by kategengler** [comment]
👋 I finally finished setting this up!
